seeder:
  file: ./seeder/seeder.rb
  disabled: false

parsers:
  - file: ./parsers/listings.rb
    page_type: listings
    disabled: false

  - file: ./parsers/details.rb
    page_type: details
    disabled: false

exporters:
  - file: ./exporters/products_json.yaml
    disabled: false
    
  - file: ./exporters/products_csv.yaml
    disabled: false